# Generated by Django 4.2.6 on 2023-11-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('place', models.CharField(max_length=30)),
            ],
        ),
    ]
